CROSS_COMPILE ?= x86_64-w64-mingw32-
CXX = $(CROSS_COMPILE)g++
CC = $(CROSS_COMPILE)gcc
AR = $(CROSS_COMPILE)ar
RC = $(CROSS_COMPILE)windres
DLLTOOL = $(CROSS_COMPILE)dlltool

SALAMAND_DIR = ../salamander-plugins/salamand
SHARED_DIR = ../salamander-plugins/salamand/plugins/shared

CXXFLAGS = -O2 -Wall -Wno-unknown-pragmas -Wno-unused-variable -Wno-unused-function -Wno-parentheses -std=c++17 \
    -DWIN32 -D_WIN32 -D_WINDOWS -D_USRDLL -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 \
    -D_CRT_SECURE_NO_WARNINGS -DUNICODE_NOT_USED -D_FILE_OFFSET_BITS=64 \
    -Isrc -Isrc/lang -Isrc/libssh2/include -I$(SHARED_DIR) -I$(SALAMAND_DIR)

CFLAGS = -O2 -Wall -Wno-unknown-pragmas -Wno-unused-variable -Wno-unused-function -Wno-parentheses \
    -DWIN32 -D_WIN32 -D_WINDOWS -D_USRDLL -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 \
    -D_CRT_SECURE_NO_WARNINGS \
    -Isrc/libssh2/include

LDFLAGS = -shared -s -static -static-libgcc -static-libstdc++ \
    -Wl,--start-group libssh2_static.a libcrypto-3-x64.a -Wl,--end-group \
    -lws2_32 -lshlwapi -lcomctl32 -lcomdlg32 -lole32 -lshell32 -lgdi32 -lmsimg32 -luxtheme -ldwmapi -lbcrypt -lcrypt32

# libssh2 static library (OpenSSL backend)
LIBSSH2_CFLAGS = -O2 -Wall -Wno-unused-variable -Wno-unused-function \
    -DWIN32 -D_WIN32 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 \
    -DLIBSSH2_OPENSSL -DLIBSSH2_MD5_ENABLE -DLIBSSH2_DSA_ENABLE \
    -Isrc/libssh2/include -Isrc/libssh2 -Isrc

LIBSSH2_SRCS = \
    src/libssh2/agent.c \
    src/libssh2/bcrypt_pbkdf.c \
    src/libssh2/chacha.c \
    src/libssh2/channel.c \
    src/libssh2/cipher-chachapoly.c \
    src/libssh2/comp.c \
    src/libssh2/crypt.c \
    src/libssh2/global.c \
    src/libssh2/hostkey.c \
    src/libssh2/keepalive.c \
    src/libssh2/kex.c \
    src/libssh2/knownhost.c \
    src/libssh2/mac.c \
    src/libssh2/misc.c \
    src/libssh2/openssl.c \
    src/libssh2/packet.c \
    src/libssh2/pem.c \
    src/libssh2/poly1305.c \
    src/libssh2/publickey.c \
    src/libssh2/scp.c \
    src/libssh2/session.c \
    src/libssh2/sftp.c \
    src/libssh2/transport.c \
    src/libssh2/userauth.c \
    src/libssh2/userauth_kbd_packet.c \
    src/libssh2/version.c

LIBSSH2_OBJS = $(LIBSSH2_SRCS:.c=.o)

CPP_SRCS = \
    src/sftpconn.cpp \
    src/sftpglue.cpp \
    src/sftp.cpp \
    src/dialogs.cpp \
    src/fs1.cpp \
    src/fs2.cpp \
    src/menu.cpp \
    src/archiver.cpp \
    src/viewer.cpp \
    src/thumbldr.cpp \
    $(SHARED_DIR)/auxtools.cpp \
    $(SHARED_DIR)/dbg.cpp \
    $(SHARED_DIR)/mhandles.cpp \
    $(SHARED_DIR)/winliblt.cpp \
    $(SHARED_DIR)/plugindarkmode.cpp

CPP_OBJS = $(CPP_SRCS:.cpp=.o)

ALL_OBJS = $(CPP_OBJS) src/sftp.res

all: libcrypto-3-x64.a libssh2_static.a sftp.spl english.slg czech.slg

libcrypto-3-x64.a: libcrypto-3-x64.def
	$(DLLTOOL) -m i386:x86-64 -d $< -l $@ -D libcrypto-3-x64.dll

src/libssh2/%.o: src/libssh2/%.c
	$(CC) $(LIBSSH2_CFLAGS) -c $< -o $@

libssh2_static.a: $(LIBSSH2_OBJS)
	$(AR) rcs $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

src/sftp.res: src/sftp.rc
	cd src && $(RC) -O coff -I. -Ilang -I$(CURDIR)/$(SHARED_DIR) -I$(CURDIR)/$(SALAMAND_DIR) -i sftp.rc -o sftp.res

src/lang/lang_en.res: src/lang/lang_en.rc
	cd src/lang && $(RC) -O coff -I. -I.. -I$(CURDIR)/$(SHARED_DIR) -I$(CURDIR)/$(SALAMAND_DIR) -i lang_en.rc -o lang_en.res

src/lang/lang_cs.res: src/lang/lang_cs.rc
	cd src/lang && $(RC) -O coff -I. -I.. -I$(CURDIR)/$(SHARED_DIR) -I$(CURDIR)/$(SALAMAND_DIR) -i lang_cs.rc -o lang_cs.res

sftp.spl: libssh2_static.a libcrypto-3-x64.a $(ALL_OBJS) src/sftp.def
	$(CXX) -shared src/sftp.def $(ALL_OBJS) $(LDFLAGS) -o $@

english.slg: src/lang/lang_en.res
	$(CXX) -shared -nostdlib -Wl,-e,0 $< -o $@

czech.slg: src/lang/lang_cs.res
	$(CXX) -shared -nostdlib -Wl,-e,0 $< -o $@

clean:
	-del /Q /F $(subst /,\,$(CPP_OBJS)) $(subst /,\,$(LIBSSH2_OBJS)) 2>nul
	-del /Q /F src\sftp.res src\lang\lang_en.res src\lang\lang_cs.res 2>nul
	-del /Q /F sftp.spl english.slg czech.slg libssh2_static.a libcrypto-3-x64.a 2>nul
